export const program1 = {
    params: {
        nCols: 8,
        nColsMask: 8,
        useOffset: false,
        mirror: true,
        mirrorHalf: false,
        mirrorOffset: false,
        mask: false,
        animationSpeed: 0,
    },
    material1: {
        useOffset: true,
        stripes: 2.0,
        metalness: 0.5,
        roughness: 0.0,
        ambientIntensity: 0.2,
        aoMapIntensity: 1.0,
        envMapIntensity: 1.0,
        displacementScale: 0.0,
        normalScale: 0.0,
        color1: 0xffffff,
        playWave: false,
        waveSpeed: 0.0,
        waveSizeX: 0.0,
        waveSizeY: 0.0,
        waveFrequency: 0.0,
        rainbowX: 0.0,
        rainbowY: 0.0,
        rainbowZ: 0.5,
        blurRadius: 0.0,
        blurResX: 0.0,
        blurResY: 0.0,
    },
    material2: {
        useOffset: true,
        stripes: 2.0,
        metalness: 0.5,
        roughness: 0.0,
        ambientIntensity: 0.0,
        aoMapIntensity: 1.0,
        envMapIntensity: 1.0,
        displacementScale: 0.0,
        normalScale: 0.0,
        color1: 0xffffff,
        playWave: false,
        waveSpeed: 1.0,
        waveSizeX: 0.0,
        waveSizeY: 0.0,
        waveFrequency: 1.0,
        rainbowX: 0.5,
        rainbowY: 0.1,
        rainbowZ: 0.0,
        blurRadius: 0.0,
        blurResX: 0.0,
        blurResY: 0.0,
    },
};

export const program2 = {
    params: {
        nCols: 2,
        nColsMask: 8,
        useOffset: false,
        mirror: false,
        mirrorHalf: false,
        mirrorOffset: false,
        mask: false,
        animationSpeed: 0,
    },
    material1: {
        useOffset: true,
        stripes: 0.0,
        metalness: 0.4,
        roughness: 0.4,
        ambientIntensity: 0.2,
        aoMapIntensity: 1.0,
        envMapIntensity: 1.0,
        displacementScale: 0.1,
        normalScale: 0.0,
        color1: 0xffffff,
        playWave: true,
        waveSpeed: 0.01,
        waveSizeX: 0.04,
        waveSizeY: 0.0,
        waveFrequency: 1.0,
        rainbowX: 0.0,
        rainbowY: 0.0,
        rainbowZ: 0.0,
        blurRadius: 0.0,
        blurResX: 0.0,
        blurResY: 0.0,
    },
    material2: {
        useOffset: true,
        stripes: 0.0,
        metalness: 0.0,
        roughness: 0.0,
        ambientIntensity: 0.0,
        aoMapIntensity: 1.0,
        envMapIntensity: 1.0,
        displacementScale: 0.0,
        normalScale: 0.0,
        color1: 0xffffff,
        playWave: false,
        waveSpeed: 1.0,
        waveSizeX: 0.0,
        waveSizeY: 0.0,
        waveFrequency: 1.0,
        rainbowX: 0.0,
        rainbowY: 0.0,
        rainbowZ: 0.0,
        blurRadius: 0.0,
        blurResX: 0.0,
        blurResY: 0.0,
    },
};
